C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/4,3/
      DATA (SPROP(I,-1,1),I=1,8)/-11,-11,-11,-11,11,11,11,11/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/5,-1/
      DATA (SPROP(I,-2,1),I=1,8)/24,24,24,24,-24,-24,-24,-24/
      DATA TPRID(-2,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/5,4/
      DATA (SPROP(I,-1,2),I=1,8)/24,24,24,24,-24,-24,-24,-24/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/-1,3/
      DATA (SPROP(I,-2,2),I=1,8)/24,24,24,24,-24,-24,-24,-24/
      DATA TPRID(-2,2)/0/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA (IFOREST(I,-1,3),I=1,2)/5,4/
      DATA (SPROP(I,-1,3),I=1,8)/24,24,24,24,-24,-24,-24,-24/
      DATA TPRID(-1,3)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/1,3/
      DATA TPRID(-2,3)/2/
      DATA (SPROP(I,-2,3),I=1,8)/0,0,0,0,0,0,0,0/
      DATA (IFOREST(I,-3,3),I=1,2)/-2,-1/
C     Diagram 4
      DATA MAPCONFIG(4)/4/
      DATA (IFOREST(I,-1,4),I=1,2)/5,4/
      DATA (SPROP(I,-1,4),I=1,8)/24,24,24,24,-24,-24,-24,-24/
      DATA TPRID(-1,4)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/1,-1/
      DATA TPRID(-2,4)/1/
      DATA (SPROP(I,-2,4),I=1,8)/0,0,0,0,0,0,0,0/
      DATA (IFOREST(I,-3,4),I=1,2)/-2,3/
C     Number of configs
      DATA MAPCONFIG(0)/4/
