ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMWgamma_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_47 = ', GC_47
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_99 = ', GC_99
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_102 = ', GC_102
