C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(1,2)*P(2,3)*P(3,1)) + P(1,3)*P(2,1)*P(3,2) +
C      P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) - P(-1,1)*P(-1,3)*P(3,2)*Metr
C     ic(1,2) - P(-1,2)*P(-1,3)*P(2,1)*Metric(1,3) +
C      P(-1,1)*P(-1,2)*P(2,3)*Metric(1,3) + P(-1,1)*P(-1,3)*P(1,2)*Metr
C     ic(2,3) - P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVV2_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 TMP2
      COMPLEX*16 TMP12
      COMPLEX*16 V3(*)
      COMPLEX*16 TMP11
      REAL*8 P1(0:3)
      COMPLEX*16 TMP10
      REAL*8 P2(0:3)
      COMPLEX*16 TMP7
      REAL*8 P3(0:3)
      COMPLEX*16 TMP6
      COMPLEX*16 TMP5
      COMPLEX*16 TMP4
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP13
      COMPLEX*16 COUP
      COMPLEX*16 TMP9
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP3
      COMPLEX*16 TMP8
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      TMP3 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP9 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP8 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP2 = (P3(0)*V2(3)-P3(1)*V2(4)-P3(2)*V2(5)-P3(3)*V2(6))
      TMP5 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      TMP4 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP7 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP6 = (P3(0)*V1(3)-P3(1)*V1(4)-P3(2)*V1(5)-P3(3)*V1(6))
      TMP11 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      TMP10 = (P3(0)*P1(0)-P3(1)*P1(1)-P3(2)*P1(2)-P3(3)*P1(3))
      TMP13 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP12 = (P2(0)*P1(0)-P2(1)*P1(1)-P2(2)*P1(2)-P2(3)*P1(3))
      VERTEX = COUP*(TMP10*(-CI*(TMP3*TMP13)+CI*(TMP7*TMP8))+(TMP11*(
     $ -CI*(TMP2*TMP12)+CI*(TMP5*TMP9))+(TMP4*(-CI*(TMP8*TMP9)+CI
     $ *(TMP2*TMP3))+TMP6*(-CI*(TMP5*TMP7)+CI*(TMP12*TMP13)))))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(1,2)*P(2,3)*P(3,1)) + P(1,3)*P(2,1)*P(3,2) +
C      P(-1,2)*P(-1,3)*P(3,1)*Metric(1,2) - P(-1,1)*P(-1,3)*P(3,2)*Metr
C     ic(1,2) - P(-1,2)*P(-1,3)*P(2,1)*Metric(1,3) +
C      P(-1,1)*P(-1,2)*P(2,3)*Metric(1,3) + P(-1,1)*P(-1,3)*P(1,2)*Metr
C     ic(2,3) - P(-1,1)*P(-1,2)*P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVV2_3_0(V1, V2, V3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 P3(0:3)
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 TMP
      COMPLEX*16 V3(*)
      REAL*8 P2(0:3)
      COMPLEX*16 V2(*)
      REAL*8 P1(0:3)
      COMPLEX*16 VERTEX
      COMPLEX*16 V1(*)
      CALL VVV2_0(V1,V2,V3,COUP1,VERTEX)
      CALL VVV3_0(V1,V2,V3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


